# Generated by Django 5.1 on 2024-08-13 13:50

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(help_text='Enter your name here', max_length=64, verbose_name='Name')),
                ('last_name', models.CharField(help_text='Enter your surname here', max_length=64, verbose_name='Фамилия')),
                ('email', models.EmailField(help_text='Enter your email here', max_length=254, unique=True, verbose_name='email address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Enter your phone number here', max_length=128, region=None, verbose_name='Phone number')),
                ('role', models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='user', help_text="Enter users' role here", max_length=20, verbose_name='User role')),
                ('image', models.ImageField(blank=True, help_text='Attach your avatar here', null=True, upload_to='photos/', verbose_name='avatar')),
                ('is_active', models.BooleanField(default=True, help_text='Is your status active?', verbose_name='Active status')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
