version: '3'

services:

  redis:
    image: redis
    ports:
      - '6379:6379'
    restart: always

  db:
    restart: always
    image: postgres
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata

  app:
    build: .
    tty: true
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      - db



volumes:
  pg_data:
