# Generated by Django 5.0.8 on 2024-08-13 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Attach a photo of your product', null=True, upload_to='images/', verbose_name='Photo')),
                ('title', models.CharField(help_text='Type your product title here', max_length=200, verbose_name='Product title')),
                ('price', models.PositiveIntegerField(help_text='Type your product price here', verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Add creation date')),
                ('description', models.CharField(blank=True, help_text='Type your product description here', max_length=1000, null=True, verbose_name='Product description')),
                ('author', models.ForeignKey(default='Anonymous', help_text="Choose ads' author", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ad author')),
            ],
            options={
                'verbose_name': 'Ad',
                'verbose_name_plural': 'Ads',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Leave your comment here', max_length=1000, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Comment add time')),
                ('ad', models.ForeignKey(help_text='Ad to which you leave comment', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.ad', verbose_name='Ads')),
                ('author', models.ForeignKey(help_text='Choose author', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Comment author')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ('-created_at',),
            },
        ),
    ]
